FROM sconecuratedimages/muslgcc:alpine-scone5 as builder
WORKDIR /app
COPY cowsay.c cowsay.c
RUN x86_64-alpine-linux-musl-gcc -o cowsay cowsay.c -static

FROM scratch
LABEL CECI_EST_UN_SECRET "QmllbiBqb3XDqSwgdHUgYXMgc3UgdHJvdXZlciBldCBkw6ljb2RlciBsZSBtZXNzYWdlIHNlY3JldCAhIQpQdWJsaWNpcyBTYXBpZW50IGNoZXJjaGUgZGVzIGdlbnMgcGFzc2lvbm7DqXMgcG91ciBsZXMgcmVqb2luZHJlLCBzaSB0dSBhcyB0cm91dsOpIGNlIG1lc3NhZ2UgdHUgZW4gZmFpcyBzdXJlbWVudCBwYXJ0aS4KVHUgcGV1eCB0ZW50ZXIgdGEgY2hhbmNlIGVuIGVudm95YW50IHRvbiBDViDDoCB0ZWFtcmVjcnV0ZW1lbnRAcHVibGljaXNzYXBpZW50LmNvbQoKVHUgcGV1eCDDqWdhbGVtZW50IG5vdXMgY29udGFjdGVyLCBBbGV4aXMgIkhvcmdpeCIgQ2hvdGFyZCBldCBGcmFuY2sgQ3Vzc2FjIHBvdXIgc2ltcGxlbWVudCBwYXJ0YWdlciBhdmVjIG5vdXMgY2UgcXVlIHR1IGFzIHBlbnPDqSBkZSBub3RyZSBhcnRpY2xlLgpmcmFuY2suY3Vzc2FjQHB1YmxpY2lzc2FwaWVudC5jb20KYWxleGlzLmNob3RhcmRAcHVibGljaXNzYXBpZW50LmNvbQoKTWVyY2kgZCdhdm9pciBjaGVyY2jDqSwgw6dhIG5vdXMgZmFpdCB0csOocyBwbGFpc2lyIDopCgo="
COPY --from=builder /app/cowsay /cowsay
ENTRYPOINT ["/cowsay"]
CMD ["Un message secret se trouve dans cette image, sauras-tu le trouver ?"]

